name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sbsrf/librime
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.sbsrf }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          shopt -s nullglob
          mv sbxlm/* .
          zip -r sbsrf.zip lua opencc . -x "*.zip"
          cd extra
          zip -r ../extra.zip .
          cd ..
          ls -la *.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            sbsrf.zip
            extra.zip
      - name: notice
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://5b042a5455e0480fa806fc9483f9a8a1-cn-chengdu.alicloudapi.com/external/v1/releases/notifications?key=sbsrf'
          method: 'GET'
